#!/bin/sh
if test $# -lt 3; then echo "Usage: $0 confdir profiledir gendir" >&2; exit 1; fi;
confdir="$1";
profiledir="$2";
gendir="$3";

rm --interactive=never --recursive -- "$gendir/gen";
mkdir -p "$gendir/gen/interfaces" || exit 4;

gen-interface-skeletons "$confdir" "$gendir/gen/interfaces" || exit 16;
#gen-includes "chains" <"$confdir/include-chains" > "$gendir/gen/chain-includes.conf"
gen-dependency-list "$confdir" "$profiledir" | gen-includes "chains" > "$gendir/gen/dependency-includes.conf";
